### ISSUE TITLE
Better classpath support in settings?

### ISSUE THREAD

**Issue by nickbattle** [jonaskrask/vdm-vscode#69] opened 2021-12-04 20:04 UTC
We've talked about this before, but I don't think there's an issue for it yet.

We're collecting lots of different cases where the server classpath needs to be manipulated. We currently just have annotation paths. But we will also need "plugin paths" for jars like Leo's Isabelle plugin (and arbitrary plugins in future). And those plugins may well depend on 3rd party jars that also need to be added.

The current annotation paths setting is a bit awkward, especially if the line gets quite long. Would it be possible to have a general "Classpath additions" setting that uses a widget like the Files/include and Files/exclude setting? That has a list of entries, each of which can be deleted or edited, and at the end there is an "Add Entry" button. That would be much cleaner and would cover all bases (the text could explain that the setting is used for annotations, plugins or general classpath additions).

I think it would be clearer if we simply allow jars or folders, like a standard classpath. I think the current annotation paths tries to be "helpful" and searches a folder name for contained jars. That's not a standard thing really? It may cause more confusion than needed?

**Comment by jonaskrask** [comment] 2021-12-04 20:42
Would be a good idea to have a more user-friendly way to set these than in one long line...

The annotationsPaths entry was changed to a classpathAdditions entry without it trying to be "helpful" in issue #22, but it was never moved to the development branch... will do that first thing Monday, when I have a chance to check that I agree with the implementation.

**Comment by nickbattle** [comment] 2021-12-04 21:01
OK, that's good. The "Files" settings is pretty easy to use by comparison, if that can be "copied".

**Comment by jonaskrask** [comment] 2021-12-04 21:29
I see, it seems pretty easy copy

**Comment by jonaskrask** [comment] 2021-12-06 11:42
The change to class path additions as a string array is implemented on the branch "issue22" in the VSIX. @nickbattle will you give it a try?

**Comment by nickbattle** [comment] 2021-12-06 11:52
That's a huge improvement over a one-liner!

I added one entry, with Leo's plugin jar. I notice that it appears after the VDMJ jars, but before the standard annotations jar:

-cp /home/nick/.vscode/extensions/jonaskrask.vdm-vscode-1.2.2/resources/jars/vdmj-4.4.4-SNAPSHOT-211119.jar:
/home/nick/.vscode/extensions/jonaskrask.vdm-vscode-1.2.2/resources/jars/lsp-4.4.4-SNAPSHOT-211119.jar:
**/home/nick/.vscode/vdm2isa-4.4.4-SNAPSHOT-211119.jar:**
/home/nick/.vscode/extensions/jonaskrask.vdm-vscode-1.2.2/resources/jars/annotations-4.4.4-SNAPSHOT-211119.jar

I was expecting the classpath additions to be on the end? :-)

Is it possible to add a "Find" button, in addition to the OK/Cancel, to open a *.jar/dir search dialog? Things like "Add folder to workspace" do this - it would be very helpful.

**Comment by jonaskrask** [comment] 2021-12-06 11:59
TBH I can't remember why the standard annotations are after the user added ones, but I remember it as if there was a reason...?

I can see what I can do about adding a "Find" button. Not sure it is doable from settings though. Alternatively, it can be implemented as a command?

**Comment by nickbattle** [comment] 2021-12-06 12:03
Ah yes, it might be to do with overriding annotations. So in principle, you could create your own version of (say) @Printf and put that on the classpath ahead of the standard one, which would get loaded in preference. Hmm... that makes sense I suppose. And you wouldn't do the same with VDMJ/LSP because they're fundamental.

OK... happy with that.

If you can find a Finder, great; if not, I guess it's still a massive improvement.

**Comment by jonaskrask** [comment] 2021-12-06 14:25
I can create a finder for the files, but I don't really seem to have a way to determine if the user is trying to edit global/workspace/folder settings, so have to save the selected files somewhere fixed. My immediate intuition would be to save the additions to the workspace (and not globally). What would you think?

**Comment by nickbattle** [comment] 2021-12-06 14:34
Not sure what you mean. I wasn't intending the Finder to move/access the files, but just to populate the settings with the full pathname of the selected file or folder. Can't we do that?

**Comment by jonaskrask** [comment] 2021-12-06 14:46
Yes, but the issue is that the settings can apply to different scopes (global, workspace, folder), and I can't find a way to determine which tab the user is in (see picture)
![image](https://user-images.githubusercontent.com/17763798/144866619-2f35d2e9-f9a3-4859-8812-909071cde14b.png)

**Comment by nickbattle** [comment] 2021-12-06 14:54
So how did this work when the class path additions was a simple text field? (Sorry, I'm probably missing something!)

**Comment by jonaskrask** [comment] 2021-12-06 15:04
No worries :)
When it is added manually (using "Add Item") it is determined by the tap that the user is in.
To implement the "Find" functionality it has to be a command, and in that command, I can't see which tap is open.  But, I think I found a "solution"

**Comment by jonaskrask** [comment] 2021-12-06 15:36
Now with find functionality :)

**Comment by nickbattle** [comment] 2021-12-06 21:13
Hmm. It does work - the folder or file appears in the .settings.json file. But it's confusing when it doesn't appear in the settings "dialogue" you'reseeing because you're looking at (say) User settings and you added the file to Folder settings.

Would it help if the Find button was part of the line that pops up when you click "Add Item"? I mean it doesn't have to decide which file to update, it can just return a path string to the dialogue and populate the field. In a sense, it's like the "Edit" button, except it pops up a dialogue. Or can't it work like that?

**Comment by jonaskrask** [comment] 2021-12-07 08:15
Totally agree that it is confusing.
Adding the "Find" option as part of the "Add Item" line would be optimal, but that does not seem possible..
I have tried to make the command automatically determine if you are looking at user settings or one of the others, but it seems that it is not possible.
I have not been able to find any other extensions that do anything similar, so can't draw inspiration from anywhere, and the API is at times very scarcely documented...
Hence, I think the current behavior is the best that I can do at the moment.

**Comment by nickbattle** [comment] 2021-12-07 09:54
Is there something like a StackExchange topic where we can ask questions?  But I understand: it's a complicated system, and we're not experts, so it can be frustrating. That's why I stick to hacking VDMJ :^)

**Comment by jonaskrask** [comment] 2021-12-07 11:13
I have tried to post a question on StackOverflow, then we will see if someone has an idea. If not I will close the issue with the current behavior :)

**Comment by jonaskrask** [comment] 2021-12-07 13:27
According to a user on StackOverflow: "You can't modify the Settings GUI, There is no hook in the Settings page to get notified of a tab change"

Will re-open if new info arrives.

**Closed by jonaskrask** 2021-12-07 13:27 UTC
Labels: enhancement
