### ISSUE TITLE
CT - execute request failed: Error: Connection got disposed

### ISSUE THREAD

**Issue by nickbattle** [jonaskrask/vdm-vscode#16] opened 2021-01-30 21:54 UTC
I'm testing a combinatorial test on quite a large specification (though the trace expansion is modest). When I use the jars built into the extension to run all tests, I usually get the error above in the logs, and the CT run hangs. But when I try to run the same thing connecting to an external experimental server, it's fine.

I've added symlinks to the latest jars in the 1.0.4 extension resources folder. I'm assuming that makes no difference?
I tried running with the original 1.0.4 jars, but it's the same.

The error appears in the `logs/<datetime>/exthost1/jonasrask.vdm-vscode/static.model_client.log` file. Just one line.

I was working in a workspace, but only one project was open.

I'll try to attach a ZIP of the model... [fmi3.zip](https://github.com/jonaskrask/vdm-vscode/files/5898775/fmi3.zip)

**Comment by nickbattle** [comment] 2021-01-30 21:58
After the hang, I see that the VDMJ/LSP server process is still there - it hasn't crashed or closed itself down. Perhaps we can try somehow with the built-in jar, but with diagnostics on for the server, in case the server is closing the connection in some way?

**Comment by nickbattle** [comment] 2021-01-31 09:31
I've managed to turn on the server logging. It seems to get up to test 223 or thereabouts and then just seems to stop. But only when it is executed via the VSCode UI. Stand-alone it sails through as normal. I tried changing the -Xmx setting, but it doesn't make a big difference. Curious.

```
09:16:47.057: Starting batch at test number 211...
09:16:47.096: Completed batch at test number 221
09:16:47.097: Sending work done = 48%
09:16:47.097: <<< LSP { "jsonrpc" : "2.0", "method" : "$/progress", "params" : { "token" : "CombinatorialTestToken-16120846058731", "value" : { "kind" : "report", "message" : "Processing DEFAULT`SVInvariantTotal", "percentage" : 48 } } }
09:16:47.097: Sending intermediate results
09:16:47.098: ...
09:16:47.098: Starting batch at test number 221...
<hangs>
09:16:51.178: >>> LSP {"jsonrpc":"2.0","method":"$/cancelRequest","params":{"id":4}}
09:16:51.178: Thread 4 cancel sent
09:20:13.346: >>> LSP {"jsonrpc":"2.0","id":5,"method":"shutdown","params":null}
09:20:13.346: <<< LSP { "jsonrpc" : "2.0", "result" : null, "id" : 5 }
09:20:13.394: >>> LSP {"jsonrpc":"2.0","method":"exit","params":null}
```

**Comment by jonaskrask** [comment] 2021-01-31 09:46
I am able to (somewhat) recreate the issue. For me the server is able to complete the first execution (outline -> generate -> execute), however if I try to re-run the test (generate -> execute) it hang after the first batch every time.

For me the log message "CT - execute request failed: Error: Connection got disposed" is logged when I close VSCode, not before. That is, it is caused by the premature closing of VSCode, so I don't think it is related to the issue.

**Comment by nickbattle** [comment] 2021-01-31 09:48
Ah, OK, that's a clue. So we're looking for a reason why VDMJ just stops at some point. Does it always run through for you with an external server?  With me it's always stopping in batch 221-231, is that the same for you?

**Comment by nickbattle** [comment] 2021-01-31 09:50
Oh! One thought... there are a lot of @OnFail messages produced by this test. What happens to the stdout stream for the process? If that went somewhere and then clogged up when a buffer was full, it might explain why it seems to hang, waiting for the IO to be drained (but only in the UI)?

**Comment by jonaskrask** [comment] 2021-01-31 09:55
Yes, using an external server it always run through. 

We are not accessing the stdout stream for the process, so maybe it that..

**Comment by nickbattle** [comment] 2021-01-31 09:57
I tried removing the annotations jar, but then it won't start the server. That would normally have the effect of turning off the annotations. Can you "hack" that and try it?

**Comment by nickbattle** [comment] 2021-01-31 09:58
In general, we should probably capture the stdout/stderr into log files somewhere. It only really affects CT - the DAP process naturally deals with it.

**Comment by jonaskrask** [comment] 2021-01-31 10:01
Removing the annotations jar seems to do the trick, so it is probably stdout that is the issue.
Would you rather have stdout/stderr captured in a terminal window or a log file?

**Comment by nickbattle** [comment] 2021-01-31 10:04
The VSCode way seems to be to use log files? This is only a CT thing really: other executions will naturally send output via the DAP protocol. Occasionally something may explode and produce a stderr stacktrace, so that would be useful in a log file. We can warn people that a CT with annotations  may produce a LOT of logging!

**Comment by jonaskrask** [comment] 2021-01-31 10:30
It seems to be creating a lot of logging, so maybe it is better for the user to just have it available through an output window instead of a log, that way you don't have to navigate to some obscure log folder to find it either :)

A fast implementation of this provides the following view:
![image](https://user-images.githubusercontent.com/17763798/106381240-a8f92f80-63b7-11eb-8be4-e7bd5d00703c.png)

**Comment by nickbattle** [comment] 2021-01-31 10:35
OK, that's a nice idea. But I would want to know that the console logging didn't slow down the CT trace significantly - especially if the log gets large and the scrolling is expensive (relatively).  Can you try some performance experiments with a console vs. writing to a file?

**Comment by jonaskrask** [comment] 2021-01-31 10:58
I have done a small performance test using the specification from this issue.
I have tried 3 different cases: logging to a file, output to window, discard messages (read stdout but do nothing with it).

I get the following execution times:
![image](https://user-images.githubusercontent.com/17763798/106381792-8832d900-63bb-11eb-862f-3d6ab88548fd.png)

**Comment by nickbattle** [comment] 2021-01-31 11:02
Nice test :-)  OK, so it does not seem to make a huge difference. And it is sometimes a nice feature to have. I'm a bit nervous though... would it be easy to add a "setting" that enables or disables logging to a terminal? The default could safely be to enable it. That way we have a way out, if it causes issues.

**Comment by jonaskrask** [comment] 2021-01-31 11:09
Yes that is no problem at all, should it just discard the stdout messages if the setting is disabled?

**Comment by nickbattle** [comment] 2021-01-31 11:13
Well, for complete flexibility we could say no setting means write to a console, a blank setting means disable output (or "/dev/null"), and a setting with a filename writes to that file? :-) Do we treat stdout and stderr the same way, or should there be an option for each?

**Comment by jonaskrask** [comment] 2021-01-31 11:57
It seems like it is the same messages that are output to stderr and stdout, can you clarify the difference?

**Comment by nickbattle** [comment] 2021-01-31 12:00
That shouldn't be the case. Most (all?) of the annotations write to stdout, I believe. I can check later if that's in doubt, but we would see a lot of double-messaging from the command line if that was the case. (Will be away for an hour or two...)

**Comment by jonaskrask** [comment] 2021-01-31 12:06
Ups.. my bad, made a stupid copy-paste error. I will push a solution to this shortly on the development branch, will you check it out later?

**Comment by nickbattle** [comment] 2021-01-31 13:32
OK, I'll try to take a look at it this afternoon. Thanks for the quick fix - and on a Sunday too :-)

**Comment by nickbattle** [comment] 2021-01-31 14:38
I just tried the 1.0.5 development VSIX, and it seems to work. It's a bit confusing because when the "active" flag is checked, the setting is removed from the file rather than being set to "true" (which is the default). I can see why, but it's confusing to check something and have the entry disappear.

The description should be "**Activate** Stdio Logging" (not "Active")?

In the path description, I'd add a comma after "If empty"?

**Comment by jonaskrask** [comment] 2021-02-01 07:29
I see why it is a bit confusing that the setting is removed on the default value, but I don't think there is anything we can do about it..

I will make the two changes you have mentioned.

**Closed** 2021-02-01 07:35 UTC
Labels: bug
