### ISSUE TITLE
CodeLens requests may send $/cancelRequest

### ISSUE THREAD

**Issue by nickbattle** [jonaskrask/vdm-vscode#86] opened 2021-12-28 09:34 UTC
If the response to a textDocument/codeLens takes longer than about 7ms, the client follows up with a $/cancelRequest, even though the response to the codeLens has been received:
```
09:26:52.431: [FINE][1] >>> LSP {"jsonrpc":"2.0","id":1,"method":"textDocument/codeLens","params":{"textDocument":{"uri":"file:///home/nick/vscode.tests/TestSL/modules.vdmsl"}}}
09:26:52.444: [FINE][1] <<< LSP { "jsonrpc" : "2.0", "result" : [ { "range" : { "start" : ... } ], "id" : 1 }
09:26:52.445: [FINE][1] >>> LSP {"jsonrpc":"2.0","method":"$/cancelRequest","params":{"id":1}}
09:26:52.446: [SEVERE][1] ERROR: Cannot cancel thread id 1
```
Here, the codeLens took 11ms. You seem to get the cancelRequest if the codeLens takes more than ~7ms.

The cancel request fails because (a) the codeLens isn't a background task, and (b) because it has completed already. It is harmless, but it might indicate there is a timing problem? Or it might be a bug in the client, unless it's just a race between a timer and processing the response.

It may also be because I'm testing this on a 10 year old laptop!

Even if we went to a delayed codeLens model, I doubt we could return the list of unresolved lens locations in less than 7ms.

**Comment by jonaskrask** [comment] 2022-02-11 09:49
I am not able to reproduce this, maybe my PC is too fast ;)

I don't think this is an issue we can do much about. As you say it is probably a race condition between the processing of events.
I would imagine that it happens because they want to ensure a fast interface and this would then force the server to use the `codeLens/resolve` request if it is too slow.

As it says here https://microsoft.github.io/language-server-protocol/specification#dollarRequests, we are free to ignore the cancel notification, so no worries.

Closing unless you have any objections :)

**Closed by jonaskrask** 2022-02-11 09:49 UTC

**Comment by nickbattle** [comment] 2022-02-11 10:01
Yeah, my laptop is 10 years old so it's quite slow. I really just wanted to record this behaviour in case we see it again. But fine to close it - it doesn't seem to be causing a problem.
