### ISSUE TITLE
Duplicate type checking errors

### ISSUE THREAD

**Issue by paulch42** [jonaskrask/vdm-vscode#33] opened 2021-02-05 21:39 UTC
At times a type checking error is duplicated, as in the example below:

<img width="581" alt="Screen Shot 2021-02-06 at 8 19 25 am" src="https://user-images.githubusercontent.com/17345606/107090836-ea288e00-6854-11eb-9c38-c0a05cfbb633.png">

In the first case, the module does not exist. In the second case, the function does not exist. This is part of a somewhat larger and complex specification. I haven't been able to repeat it in a simpler situation, such as:

<img width="493" alt="Screen Shot 2021-02-06 at 8 31 57 am" src="https://user-images.githubusercontent.com/17345606/107091383-d0d41180-6855-11eb-9bb8-0857c405a4b5.png">

**Comment by nickbattle** [comment] 2021-02-06 08:40
Good spot. If you look very closely, the duplicates have different error numbers (3430 and 3431), but I agree that they are essentially saying the same thing and we ought to have only one. It's caused by the way type resolution works, but it should be possible to clean it up.

**Comment by nickbattle** [comment] 2021-02-06 10:42
OK, this is now fixed. It is quite hard to reproduce, but luckily one of the tests in the CSK test suite had a duplicate. Now it just has the one.

**Closed** 2021-02-14 12:52 UTC
Labels: bug, fixed in VDMJ
